In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

In [4]:
np.array([1,2,3], dtype='float32') # type 초기화 방식

array([1., 2., 3.], dtype=float32)

In [5]:
np.array([1,2,3], dtype=np.float32) # type 초기화 방식2

array([1., 2., 3.], dtype=float32)

# 처음부터 배열 만들기

size를 list or tuple로 함수들

`np.zeros((2,2))`

`np.ones((3,5))`

`np.full((2,2), 5.0)`

`np.empty((5,5))`

---

size를 각각의 파라미터로 받는 함수

`np.eye(3, 5)`

In [6]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full([2,2], 5.0)

array([[5., 5.],
       [5., 5.]])

In [9]:
np.empty((2,2))

array([[5., 5.],
       [5., 5.]])

In [10]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# np.random

정규분포로 뽑는 함수 + size를 파라미터 각각으로 받는 함수

`np.random.randn(2,2)`

---


균등분포로 뽑는 함수 + size를 파라미터 각각으로 받는 함수

`np.random.rand(2, 2)`

---

균등분포인데 size를 list or tuple로 함수들

`np.random.random((2, 2))`

`np.random.randint(0, 10, (2, 2))`

`np.random.uniform(0, 0.1, (2,2))`

In [11]:
np.random.randn(2, 2) # 표준 정규 분포

array([[ 1.05431601,  0.0313212 ],
       [ 0.20858543, -0.96049845]])

In [12]:
np.random.rand(2, 2) # [0, 1)의 균등분포

array([[0.40244853, 0.02210987],
       [0.8245346 , 0.08238093]])

In [13]:
np.random.randint(0, 10, [2, 2]) # [low, high) 범위의 정수를 균등 분포로 반환

array([[7, 8],
       [9, 5]])

In [14]:
np.random.random((2, 2)) # [0, 1)의 범위를 균등 분포로 반환
# np.random.rand()과의 차이: size 입력 파라미터

array([[0.35034622, 0.85968126],
       [0.4620513 , 0.95140301]])

In [15]:
np.random.uniform(0, 0.1, (2,2)) # [low, high) 범위의 값을 균등 분포로 반환
# np.random.random()과의 차이: 범위를 입력 가능

array([[0.05141754, 0.0319482 ],
       [0.0530711 , 0.07088853]])

In [40]:
# 1.17 이후, 아래 방식을 추천함. np.random namespace도 작동하지만 더이상 개발이 진행되지 않음.
rng = np.random.default_rng(seed=42)
rng.random((2, 2))

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803]])

In [41]:
rng.uniform(1, 2, size=(2,2))

array([[1.09417735, 1.97562235],
       [1.7611397 , 1.78606431]])

In [42]:
rng.integers(10, size=3)

array([5, 1, 8])

In [43]:
rng.integers(10, size=3)

array([4, 5, 3])

In [44]:
rng.choice(np.arange(10), 2)

array([1, 9])

# 배열 속성

`.ndim`
`.shape`
`.size`

In [271]:
a = np.random.randint(0, 10, (6, 5))
print(a.ndim)
print(a.shape)
print(a.size)

2
(6, 5)
30


# 배열 인덱싱

`start:stop:step`
-> 시작행 : stop-1행까지 : 간격

step이 -1 이면 역방향

In [322]:
x2 = np.random.randint(0, 13, [4,4])
x2

array([[12,  4,  2,  0],
       [ 2, 10,  0,  8],
       [ 5,  3,  9,  6],
       [ 0,  9, 11,  6]])

In [323]:
x2[1:2]

array([[ 2, 10,  0,  8]])

In [324]:
x2[:2, :3]

array([[12,  4,  2],
       [ 2, 10,  0]])

In [325]:
x2[::-1, ::2]

array([[ 0, 11],
       [ 5,  9],
       [ 2,  0],
       [12,  2]])

# axis

중첩 리스트: 가장 바깥쪽 리스트부터 안쪽 리스트 순으로 0부터 이름을 붙인것

- axis = 0 -> 가장 바깥
- axis = 1 -> 그다음
- axis = 2 -> 가장 안쪽

In [45]:
grid = np.arange(20).reshape(5, 2, -1)

In [46]:
grid

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [47]:
a, b = np.split(grid, [20], axis=2)
# print(a)
print(a.shape)
print(b.shape)

(5, 2, 2)
(5, 2, 0)


In [48]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [49]:
b

array([], shape=(5, 2, 0), dtype=int64)

In [50]:
grid

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [51]:
grid[0]

array([[0, 1],
       [2, 3]])

In [52]:
grid[1]

array([[4, 5],
       [6, 7]])

In [53]:
grid[:, 0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [55]:
grid = np.arange(20).reshape(2, 2, -1)
grid


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [56]:
grid.shape

(2, 2, 5)

In [57]:
grid[0, :, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
grid[:, 0, :]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [59]:
grid[1, 0, 0]

10

In [60]:
grid = np.arange(10).reshape(2, 5)
grid

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])