기본적으로 파이썬 내장함수 보다 numpy 연산이 빠름

In [1]:
import numpy as np

# 단항 ufuncs

유니버설 함수: 연산을 벡터화

In [3]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [4]:
a + 5

array([5, 6, 7, 8, 9])

In [5]:
a - 5

array([-5, -4, -3, -2, -1])

In [6]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [7]:
a % 2

array([0, 1, 0, 1, 0])

In [11]:
np.abs(a) # 파이썬 abs 함수

array([0, 1, 2, 3, 4])

In [12]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

# 고급 ufuncs

임시 배열을 생성하지 않고 지정한 배열을 이용해 메모리 위치에 직접 연산 결과를 씀

In [17]:
x = np.arange(5)
y = np.zeros(10)

# 계산된 결과를 바로 원하는 위치에 저장
np.power(2, x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [22]:
# 2 ** x 결과를 임시배열로 만든후, 그 값을 y 배열에 복사. 배열이 커지면 메모리 낭비됨
y[::2] = 2 ** x
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

# 이항 ufuncs
집계

In [23]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

## 특정 연산으로 축소
`reduce`: 결과가 하나만 남을 때까지 해당 연산을 배열 요소에 반복해서 적용. 결과를 내는 함수가 따로 존재: `np.sum` `np.prod`

`accumulate`: 중간 결과를 모두 저장. 결과를 누적하는 함수가 따로 존재 `np.cumsum` `np.cumprod`

In [24]:
np.add.reduce(x)

15

In [25]:
np.multiply.reduce(x)

120

In [26]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [28]:
M = np.random.random((3, 4))
M

array([[0.40578004, 0.98755383, 0.93432803, 0.29663502],
       [0.41379191, 0.30473727, 0.88233399, 0.49785696],
       [0.06092401, 0.90786515, 0.84561105, 0.59123054]])

In [29]:
np.min(M, axis=0)

array([0.06092401, 0.30473727, 0.84561105, 0.29663502])

In [30]:
M.min(axis=0)

array([0.06092401, 0.30473727, 0.84561105, 0.29663502])

# 브로드캐스팅
- 장점: 값의 복사가 실제로 발생하지 않음
- 규칙 1: 두 배열의 차원수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽을 1로 채운다.
- 규칙 2: 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.
- 규칙 3: 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다.

- 규칙 1: 두 배열의 차원수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽을 1로 채운다.
- 규칙 2: 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.

In [53]:
M = np.ones((3, 3))
M.shape

(3, 3)

In [34]:
a = np.arange(3)
a.shape

(3,)

In [33]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [55]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [56]:
np.arange(3).reshape(-1, 1)

array([[0],
       [1],
       [2]])

In [58]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [41]:
a = np.arange(3)[:, np.newaxis]
a

array([[0],
       [1],
       [2]])

In [42]:
b = np.arange(3)
b

array([0, 1, 2])

In [43]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [45]:
M = np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a = np.arange(3)
a

array([0, 1, 2])

In [47]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

- 규칙 1: 두 배열의 차원수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽을 1로 채운다.
- 규칙 2: 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.

In [48]:
a = np.arange(3).reshape((3,1))
a

array([[0],
       [1],
       [2]])

In [49]:
b = np.arange(3)
b

array([0, 1, 2])

In [50]:
a.shape

(3, 1)

In [51]:
b.shape

(3,)

In [52]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [59]:
X = np.random.random((10, 3))
X

array([[0.49028879, 0.62737766, 0.29905421],
       [0.61556116, 0.96455146, 0.84528857],
       [0.83805658, 0.04829462, 0.63509874],
       [0.72359153, 0.16368235, 0.00136262],
       [0.54305765, 0.91077315, 0.59076737],
       [0.00988225, 0.32434956, 0.65080801],
       [0.0810239 , 0.1291341 , 0.35688531],
       [0.05364221, 0.12352764, 0.796206  ],
       [0.56372708, 0.05367202, 0.79145457],
       [0.00519191, 0.37764351, 0.83138824]])

In [62]:
np.mean(X - X.mean(axis= 0), axis=0)

array([-1.05471187e-16, -4.99600361e-17, -4.44089210e-17])

In [63]:
a = np.arange(3)
a.shape

(3,)

In [65]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [66]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# ufuncs으로서 비교 연산자

In [67]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [68]:
x < 3

array([ True,  True, False, False, False])

In [69]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

## 요소 개수 세기
`np.count_nonzero(x)` : `True` 개수 세기

In [70]:
x = np.array([[5, 0, 3, 3], [7, 9, 3, 5], [2,4,7,6]])
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [71]:
np.count_nonzero(x)

11

In [72]:
np.count_nonzero(x<6)

8

## `np.sum()` 으로도 True 개수 세기 가능 

In [76]:
np.sum(x<6)

8

## `np.any()`: 조건에 맞는 것이 하나라도 있는가?
## `np.all()`: 조건이 모두 만족하는가?

In [77]:
np.any(x<2)

True

In [78]:
np.all(x==6)

False

In [79]:
np.any(x<2, axis=0)

array([False,  True, False, False])

In [80]:
np.all(x>2, axis=1)

array([False,  True, False])

In [82]:
np.count_nonzero((x > 0.5) & (x < 1))

0

# 마스크로서의 부울 배열 

In [87]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [85]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [88]:
x[x<5] # 조건에 맞는 값

array([0, 3, 3, 3, 2, 4])