In [1]:
import numpy as np

reshape

In [3]:
a = np.arange(1, 10)
a.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [6]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [9]:
x[np.newaxis, :]

array([[1, 2, 3]])

배열 연결

`np.concatenate([x, y])`

`np.vstack()`

`np.hstack()`

1차원

In [10]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [15]:
y = np.arange(3, 0, -1)
y

array([3, 2, 1])

In [18]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

2차원

In [20]:
grid = np.arange(1,7).reshape(2, 3)
grid

array([[1, 2, 3],
       [4, 5, 6]])

첫번째 축

In [21]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

두번째 축

In [22]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [26]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [29]:
grid = np.arange(9, 3, -1).reshape(2,3)
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [30]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [34]:
y = np.array([99, 99]).reshape(2, 1)
# y = y[:, np.newaxis]
y

array([[99],
       [99]])

In [35]:
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

배열 분할

In [37]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [41]:
np.split(x, [4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [43]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
np.vsplit(grid, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [45]:
np.hsplit(grid, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [49]:
grid = np.arange(48).reshape(3, 4, 4)
grid

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [53]:
a, b = np.vsplit(grid, [2])
print(a.shape)
print(b.shape)

(2, 4, 4)
(1, 4, 4)


In [54]:
a, b = np.hsplit(grid, [2])
print(a.shape)
print(b.shape)

(3, 2, 4)
(3, 2, 4)


In [58]:
a, b = np.dsplit(grid, [2])
print(a.shape)
print(b.shape)

(3, 4, 2)
(3, 4, 2)


In [60]:
grid = np.arange(3*4*4*4).reshape(3, 4, 4, 4)
grid

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15]],

        [[ 16,  17,  18,  19],
         [ 20,  21,  22,  23],
         [ 24,  25,  26,  27],
         [ 28,  29,  30,  31]],

        [[ 32,  33,  34,  35],
         [ 36,  37,  38,  39],
         [ 40,  41,  42,  43],
         [ 44,  45,  46,  47]],

        [[ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59],
         [ 60,  61,  62,  63]]],


       [[[ 64,  65,  66,  67],
         [ 68,  69,  70,  71],
         [ 72,  73,  74,  75],
         [ 76,  77,  78,  79]],

        [[ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95]],

        [[ 96,  97,  98,  99],
         [100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111]],

        [[112, 113, 114, 115],
         [116, 117, 118, 119],
         [120, 121, 122, 123],
         [124, 125, 126

In [66]:
np.dsplit(grid, [2])

[array([[[[  0,   1,   2,   3],
          [  4,   5,   6,   7]],
 
         [[ 16,  17,  18,  19],
          [ 20,  21,  22,  23]],
 
         [[ 32,  33,  34,  35],
          [ 36,  37,  38,  39]],
 
         [[ 48,  49,  50,  51],
          [ 52,  53,  54,  55]]],
 
 
        [[[ 64,  65,  66,  67],
          [ 68,  69,  70,  71]],
 
         [[ 80,  81,  82,  83],
          [ 84,  85,  86,  87]],
 
         [[ 96,  97,  98,  99],
          [100, 101, 102, 103]],
 
         [[112, 113, 114, 115],
          [116, 117, 118, 119]]],
 
 
        [[[128, 129, 130, 131],
          [132, 133, 134, 135]],
 
         [[144, 145, 146, 147],
          [148, 149, 150, 151]],
 
         [[160, 161, 162, 163],
          [164, 165, 166, 167]],
 
         [[176, 177, 178, 179],
          [180, 181, 182, 183]]]]),
 array([[[[  8,   9,  10,  11],
          [ 12,  13,  14,  15]],
 
         [[ 24,  25,  26,  27],
          [ 28,  29,  30,  31]],
 
         [[ 40,  41,  42,  43],
          [ 44,  45,  4